#!/usr/bin/env python3
"""Generate a bilingual, learning-first home from the existing knowledge contract."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MARKER = "Generated by scripts/build_learning_home.py; edit the generator or knowledge manifest."


def home(graph: dict, zh: bool) -> str:
    def t(cn, en):
        return cn if zh else en

    def link(cn, en, cn_path, en_path=None):
        return f"[{t(cn, en)}]({cn_path if zh else (en_path or cn_path)})"

    overview = "README_CN.md" if zh else "README.md"
    start = "start-here-cn.md" if zh else "start-here.md"
    lab = "learning-lab-cn.md" if zh else "learning-lab.md"
    curriculum = "curriculum_cn.md" if zh else "curriculum.md"
    assessment = "assessment-cn.md" if zh else "assessment.md"
    title = t("今天，从一个问题开始。", "Start with one question today.")
    lines = [
        "---\nhide:\n  - navigation\n  - toc\n---",
        f"<!-- {MARKER} -->",
        '<div class="study-home" markdown="1">',
        '<section class="dof-intro study-welcome" markdown="1">',
        '<div markdown="1">',
        f'<p class="study-eyebrow">Embodied AI · {t("学习中心", "Learning center")}</p>',
        f"# {title}",
        t(
            "先建立直觉，再推导和动手，最后用证据检查自己。选择一个起点，不必同时打开整套课程。",
            "Understand, derive, build, then check your evidence. Choose one starting point; you do not need to open the whole curriculum at once.",
        ),
        link("English", "简体中文", "index.md", "index_cn.md"),
        "</div>",
        '<div class="study-first" markdown="1">',
        f"## {t('第一次学习', 'Your first session')}",
        t(
            "从一组数组和坐标开始。一个小节只讲一个概念，带算例、图和自测。",
            "Start with arrays and coordinates. Each short lesson explains one concept with an example, a diagram and a self-check.",
        ),
        f"[{t('开始第一个知识点 →', 'Open the first concept →')}](knowledge-atlas/computing-python-numpy/numpy-axis-semantics/index.md){{ .md-button .md-button--primary }}",
        f"[{t('先做学习起点诊断', 'First, check your starting point')}]({start})",
        "</div>",
        "</section>",
        f'<aside class="study-resume" hidden data-atlas-base="{("../" if zh else "")}knowledge-atlas/" data-search-exclude>\n<p>{t("继续上次手动记住的小节：", "Continue your saved lesson:")} <a data-study-resume></a></p>\n<p class="study-home-small">{t("仅保存在本浏览器，不是课程完成记录。", "Stored only in this browser, not an assessment record.")}</p>\n<button type="button">{t("清除此书签", "Clear bookmark")}</button><span role="status"></span>\n</aside>',
        f"## {t('按现在的需要进入', 'Choose what you need now')}",
        '<div class="study-home-paths" markdown="1">',
    ]
    for cn, en, path, description_cn, description_en in [
        (
            "查懂一个概念",
            "Understand a concept",
            "knowledge-atlas/index.md",
            "从 45 章、201 个小节中定位前置知识；先读小节，必要时展开整章。",
            "Find a prerequisite across 45 chapters and 201 short lessons. The illustrated companion is Chinese-led.",
        ),
        (
            "做一次交互实验",
            "Try an experiment",
            lab,
            "改坐标、关节、控制或延迟，先预测，再看图中的变化。",
            "Change a frame, joint, controller or delay. Predict first, then inspect the change.",
        ),
        (
            "搭建一个闭环",
            "Build a closed loop",
            f"pipelines/{overview}",
            "已有基础？选择 Pipeline，按输入、阶段、产物和失败记录动手。",
            "Ready to build? Choose a Pipeline and follow its inputs, stages, artifacts and failure records.",
        ),
    ]:
        lines += [
            f'<section class="study-home-path" markdown="1">\n\n### [{t(cn, en)}]({path})\n\n{t(description_cn, description_en)}\n\n</section>'
        ]
    lines += [
        "</div>",
        f"## {t('六个阶段，逐步进入完整系统', 'Six stages toward a complete system')}",
        t(
            "下面是能力顺序，不是按阅读时长发证书。每章仍有自己的前置知识；完成一个阶段要提交相应证据。",
            "These are capability stages, not time-based certificates. Check each chapter’s prerequisites and retain the required evidence.",
        ),
        f"[{t('查看完整课程与验收安排', 'Open the curriculum and assessment plan')}]({curriculum})",
    ]
    for stage in graph["stages"]:
        relevant = [n for n in graph["nodes"] if n["stage"] == stage["id"]]
        lines += [
            f'<section class="study-stage" id="stage-{stage["id"]}" markdown="1">',
            f'<span class="study-stage-mark">L{stage["id"]}</span>',
            '<div markdown="1">',
            f"### {stage['title_zh'] if zh else stage['title']}",
            stage["exit_zh"] if zh else stage["exit"],
            " · ".join(
                f"[{n['title_zh'] if zh else n['title']}](knowledge-atlas/{n['id']}/index.md)"
                for n in relevant[:3]
            ),
        ]
        if len(relevant) > 3:
            lines += [
                f'<details markdown="1">\n<summary>{t("查看本阶段其余章节", "Other chapters in this stage")}</summary>\n\n'
                + "\n".join(
                    f"- [{n['title_zh'] if zh else n['title']}](knowledge-atlas/{n['id']}/index.md)"
                    for n in relevant[3:]
                )
                + "\n\n</details>"
            ]
        lines += ["</div>", "</section>"]
    lines += [
        f"## {t('准备好了，再进入专项与科研', 'Move into specialization when ready')}",
        link(
            "VLA 与 WAM 专项",
            "VLA and WAM tracks",
            "specializations/README_CN.md",
            "specializations/README.md",
        )
        + " · "
        + link(
            "七条科研路线",
            "Seven research routes",
            "learning-paths/README_CN.md",
            "learning-paths/README.md",
        )
        + " · "
        + link("环境配置", "Environment setup", "setup/README_CN.md", "setup/README.md"),
        f"## {t('怎样判断自己真的懂了？', 'How do you know you understand?')}",
        t(
            "能解释输入与单位，独立完成算例，改变条件后预测结果，并用代码或实验记录验证。看完文章、查看答案和记住阅读位置都不等于通过验收。",
            "Explain the inputs and units, solve an example independently, predict a changed condition, then verify with code or an experiment record. Reading a page, opening an answer or saving a bookmark is not a passed assessment.",
        ),
        f"[{t('学习验收', 'Assessment')}]({assessment}) · [{t('证据边界', 'Evidence boundaries')}](VALIDATION.md) · [{t('已有基准', 'Recorded benchmark')}](benchmark_report.md) · [{t('原始来源', 'Primary sources')}](SOURCES.md)",
        '<p class="study-home-small">'
        + t(
            "教学示例、仿真结果与真机验证分别陈述；低一层证据不能自动推出高一层结论。",
            "Teaching examples, simulation results and hardware validation are separate evidence levels. A lower level does not establish a higher one.",
        )
        + "</p>",
        "</div>",
    ]
    return "\n\n".join(lines) + "\n"


def run(check=False):
    graph = json.loads((ROOT / "knowledge/manifest.json").read_text(encoding="utf-8"))
    for zh, name in ((True, "index_cn.md"), (False, "index.md")):
        path, text = ROOT / "docs" / name, home(graph, zh)
        if check:
            if path.read_text(encoding="utf-8") != text:
                raise ValueError(f"Stale learning home: {name}")
        else:
            path.write_text(text, encoding="utf-8")
    print("Bilingual learning home verified" if check else "Bilingual learning home generated")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    run(parser.parse_args().check)
