#!/usr/bin/env python3
"""Build Chinese-led atomic lessons and responsive, offline SVG explanations.

Authored JSON is the source, not a claim of exhaustive scientific knowledge.
Normal/check modes require every existing knowledge node; --allow-partial is
only for in-progress local authoring and marks the generated index accordingly.
"""

from __future__ import annotations

import argparse
import hashlib
import html
import json
import math
import os
import re
import sys
import unicodedata
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
AUTHOR_DIR = ROOT / "knowledge/atlas"
LESSONS = ROOT / "docs/knowledge-atlas"
ASSETS = ROOT / "docs/assets/knowledge-atlas"
GENERATED_MARKER = "Generated by scripts/build_knowledge_atlas.py; edit knowledge/atlas/*.json."
KINDS = {"flow", "compare", "plot", "matrix", "timeline", "vectors", "bars"}
COLORS = ["#155e9c", "#a84413", "#5b4299", "#16705a", "#8c365f", "#596570"]
IDENTIFIER = re.compile(r"^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$")
LAB_CONNECTIONS = {
    "robot-coordinate-frames": (
        "frames",
        "固定局部点，只改变平移，再单独改变角度。预测世界坐标如何改变。",
    ),
    "robot-so3-se3": ("frames", "先用二维旋转核对正向与逆向变换；平面演示不能覆盖完整三维旋转。"),
    "robot-kinematics": (
        "kinematics",
        "把两根连杆摆成共线，观察位置可达与局部速度可控为什么不同。",
    ),
    "math-numerical-stability": (
        "kinematics",
        "比较远离奇异与接近奇异位形的 Jacobian；图不代替数值误差测试。",
    ),
    "system-feedback-control": (
        "control",
        "分别改变增益、延迟、饱和上限；每次只改一项并解释轨迹变化。",
    ),
    "robot-rigid-body-dynamics": (
        "control",
        "查看质量、力与加速度的闭环关系；这个单自由度模型不等于完整机器人。",
    ),
    "system-calibration-synchronization": (
        "timing",
        "增大推理耗时，检查动作执行时所用观测有多旧。",
    ),
    "system-realtime-safety": (
        "timing",
        "比较推理完成时刻与末步观测年龄；实时安全还需要实际看门狗与停止路径。",
    ),
    "data-episode-schema": (
        "timing",
        "区分观测采样、数据可用、推理结束与执行时刻，再检查自己的 episode 字段。",
    ),
    "learning-action-representations": (
        "timing",
        "固定预测长度 H，减小执行步数 K，观察重观测周期与动作占空比。",
    ),
    "learning-vla": (
        "timing",
        "检查一次 VLA 推理为何不等于控制周期；此实验只解释时序，不运行 VLA。",
    ),
    "math-probability-statistics": (
        "evaluation",
        "保持观察成功率不变、增大回合数，先预测区间宽度。",
    ),
    "eval-task-metrics": (
        "evaluation",
        "改变成功次数和回合数，核对分母；再讨论任务定义变化为什么无法由区间修复。",
    ),
    "eval-statistics-ablations": (
        "evaluation",
        "比较 8/10 与 80/100 的 Wilson 区间，并指出独立同分布假设。",
    ),
}
FIELDS = {
    "id",
    "node_id",
    "title",
    "english",
    "prerequisites",
    "intuition",
    "mechanism",
    "worked_example",
    "misconception",
    "check",
    "visual",
    "reading",
    "sources",
}


def esc(value) -> str:
    return html.escape(str(value), quote=True)


def finite(value) -> bool:
    return isinstance(value, (int, float)) and not isinstance(value, bool) and math.isfinite(value)


def text_lines(value: str, columns: int) -> list[str]:
    """Wrap CJK and Latin labels without relying on downloaded font metrics."""
    lines, line, occupied = [], "", 0
    for char in str(value):
        width = 2 if unicodedata.east_asian_width(char) in {"W", "F"} else 1
        if char == "\n" or occupied + width > columns:
            lines.append(line)
            line, occupied = "", 0
            if char == "\n":
                continue
        line += char
        occupied += width
    if line:
        lines.append(line)
    return lines or [""]


def number(value) -> str:
    if abs(value) < 1e-12:
        return "0"
    return f"{value:.3g}"


class SVG:
    def __init__(self, width: int, title: str, caption: str):
        self.width, self.title, self.caption = width, title, caption
        self.parts: list[str] = []
        self.text(20, 30, title, 19, columns=(width - 40) // 10, weight=650)
        self.top = 48 + 25 * (len(text_lines(title, (width - 40) // 10)) - 1)

    def text(
        self, x, y, value, size=16, *, columns=80, anchor="start", color="#172d40", weight=400
    ) -> int:
        lines = text_lines(str(value), max(4, columns))
        spans = "".join(
            f'<tspan x="{x:.2f}" dy="{0 if index == 0 else size * 1.45:.2f}">{esc(line)}</tspan>'
            for index, line in enumerate(lines)
        )
        self.parts.append(
            f'<text x="{x:.2f}" y="{y:.2f}" font-size="{size}" font-weight="{weight}" text-anchor="{anchor}" fill="{color}">{spans}</text>'
        )
        return math.ceil(len(lines) * size * 1.45)

    def line(self, x1, y1, x2, y2, color="#778797", width=1.5, dashed=False, arrow=False):
        extra = ' stroke-dasharray="5 4"' if dashed else ""
        self.parts.append(
            f'<path d="M{x1:.2f},{y1:.2f} L{x2:.2f},{y2:.2f}" fill="none" stroke="{color}" stroke-width="{width}"{extra}/>'
        )
        if arrow and math.hypot(x2 - x1, y2 - y1) > 1:
            angle = math.atan2(y2 - y1, x2 - x1)
            left = (x2 - 8 * math.cos(angle - 0.4), y2 - 8 * math.sin(angle - 0.4))
            right = (x2 - 8 * math.cos(angle + 0.4), y2 - 8 * math.sin(angle + 0.4))
            self.parts.append(
                f'<path d="M{x2:.2f},{y2:.2f} L{left[0]:.2f},{left[1]:.2f} L{right[0]:.2f},{right[1]:.2f} Z" fill="{color}"/>'
            )

    def rect(self, x, y, width, height, fill="#f0f5f9", stroke="#becbd5", radius=8):
        self.parts.append(
            f'<rect x="{x:.2f}" y="{y:.2f}" width="{width:.2f}" height="{height:.2f}" rx="{radius}" fill="{fill}" stroke="{stroke}"/>'
        )

    def circle(self, x, y, radius=4, color=COLORS[0]):
        self.parts.append(f'<circle cx="{x:.2f}" cy="{y:.2f}" r="{radius}" fill="{color}"/>')

    def finish(self, bottom: float) -> str:
        height = math.ceil(bottom + 20)
        return f'''<svg xmlns="http://www.w3.org/2000/svg" width="{self.width}" height="{height}" viewBox="0 0 {self.width} {height}" role="img" aria-labelledby="title description">
<!-- {GENERATED_MARKER} -->
<title id="title">{esc(self.title)}</title><desc id="description">{esc(self.caption)}</desc>
<rect width="100%" height="100%" fill="#ffffff"/>
<g font-family="system-ui, -apple-system, Segoe UI, PingFang SC, Microsoft YaHei, sans-serif">
{"".join(self.parts)}
</g></svg>\n'''


def visual_errors(v: dict) -> list[str]:
    if not isinstance(v, dict):
        return ["visual must be an object"]
    errors: list[str] = []
    kind = v.get("kind")
    if kind not in KINDS:
        return [f"unknown diagram kind {kind!r}"]
    for field in ("title", "caption"):
        if not isinstance(v.get(field), str) or not v[field].strip():
            errors.append(f"visual missing {field}")
    if kind == "flow":
        nodes = v.get("nodes", [])
        if not 3 <= len(nodes) <= 5:
            errors.append("flow needs 3–5 nodes")
        if any(not n.get("label") or not n.get("detail") for n in nodes):
            errors.append("flow nodes need label/detail")
        for e in v.get("edges", []):
            if not all(
                isinstance(e.get(k), int) and 0 <= e[k] < len(nodes) for k in ("from", "to")
            ) or e.get("from") == e.get("to"):
                errors.append("invalid flow edge")
    elif kind == "compare":
        panels = v.get("panels", [])
        if not 2 <= len(panels) <= 3 or any(
            not p.get("title") or not 2 <= len(p.get("lines", [])) <= 4 for p in panels
        ):
            errors.append("compare needs 2–3 titled panels of 2–4 lines")
    elif kind == "plot":
        series = v.get("series", [])
        if not 1 <= len(series) <= 3 or not v.get("x_label") or not v.get("y_label"):
            errors.append("plot needs 1–3 series and labelled axes")
        for item in series:
            points = item.get("points", [])
            if not item.get("label") or not 2 <= len(points) <= 12:
                errors.append("plot series needs label and 2–12 samples")
            elif any(
                not isinstance(p, list) or len(p) != 2 or not all(finite(x) for x in p)
                for p in points
            ):
                errors.append("plot coordinates must be finite numeric pairs")
            elif any(a[0] > b[0] for a, b in zip(points, points[1:])):
                errors.append("plot x samples must be ordered")
    elif kind == "matrix":
        values = v.get("values", [])
        if not values or len(values) > 6 or not values[0] or len(values[0]) > 6:
            errors.append("matrix must be at most 6 by 6")
        elif any(len(row) != len(values[0]) or not all(finite(x) for x in row) for row in values):
            errors.append("matrix must be rectangular and finite")
        elif len(v.get("row_labels", [])) != len(values) or len(v.get("column_labels", [])) != len(
            values[0]
        ):
            errors.append("matrix labels must match dimensions")
    elif kind == "timeline":
        events = v.get("events", [])
        if not 2 <= len(events) <= 6 or not v.get("unit"):
            errors.append("timeline needs unit and 2–6 events")
        if any(
            not e.get("label")
            or not finite(e.get("start"))
            or not finite(e.get("end"))
            or e["end"] < e["start"]
            for e in events
        ):
            errors.append("timeline events need finite ordered endpoints")
    elif kind == "vectors":
        vectors = v.get("vectors", [])
        if not 2 <= len(vectors) <= 4 or not v.get("unit"):
            errors.append("vectors needs a unit and 2–4 common-origin vectors")
        if any(
            not a.get("label") or not finite(a.get("x")) or not finite(a.get("y")) for a in vectors
        ):
            errors.append("vectors must have finite coordinates and labels")
    elif kind == "bars":
        values, labels = v.get("values", []), v.get("labels", [])
        if (
            not 2 <= len(values) <= 6
            or len(values) != len(labels)
            or not all(finite(x) for x in values)
            or not v.get("axis_label")
        ):
            errors.append("bars need equal-length labels/finite values and axis units")
    return errors


def atom_errors(atom: dict, nodes: dict) -> list[str]:
    if not isinstance(atom, dict):
        return ["atom must be an object"]
    errors = [f"missing {key}" for key in sorted(FIELDS - atom.keys())]
    if errors:
        return errors
    if not isinstance(atom["id"], str) or not IDENTIFIER.fullmatch(atom["id"]):
        errors.append("invalid atom ID")
    if atom["node_id"] not in nodes:
        errors.append("unknown parent knowledge node")
    for field in ("title", "english", "intuition"):
        if not isinstance(atom[field], str) or not atom[field].strip():
            errors.append(f"empty {field}")
    if isinstance(atom["title"], str) and any(c in atom["title"] for c in "$\\"):
        errors.append("headings must use plain text, not TeX")
    for field, minimum in (("mechanism", 3), ("worked_example", 3), ("reading", 2)):
        if (
            not isinstance(atom[field], list)
            or len(atom[field]) < minimum
            or any(not isinstance(s, str) or not s.strip() for s in atom[field])
        ):
            errors.append(f"{field} needs at least {minimum} substantive steps")
    if not isinstance(atom["prerequisites"], list):
        errors.append("prerequisites must be a list")
    if not isinstance(atom["misconception"], dict) or not isinstance(atom["check"], dict):
        return errors + ["misconception and check must be objects"]
    for key in ("wrong", "why", "right"):
        if not atom["misconception"].get(key):
            errors.append(f"misconception missing {key}")
    for key in ("question", "answer"):
        if not atom["check"].get(key):
            errors.append(f"self-check missing {key}")
    if not atom["sources"] or any(
        not s.get("title") or not re.match(r"^https?://[^/]+(?:/|$)", s.get("url", ""))
        for s in atom["sources"]
    ):
        errors.append("each atom needs a titled primary-source URL")
    serialized = json.dumps(atom, ensure_ascii=False)
    if "\ufffd" in serialized or "锟斤拷" in serialized:
        errors.append("encoding damage")
    errors.extend(visual_errors(atom["visual"]))
    return errors


def load_atoms(allow_partial=False) -> tuple[dict, list[dict], dict]:
    graph = json.loads((ROOT / "knowledge/manifest.json").read_text(encoding="utf-8"))
    nodes = {node["id"]: node for node in graph["nodes"]}
    atoms, errors, ids = [], [], set()
    for path in sorted(AUTHOR_DIR.glob("*.json")):
        content = json.loads(path.read_text(encoding="utf-8"))
        if content.get("schema_version") != 1 or not isinstance(content.get("atoms"), list):
            raise ValueError(f"{path.name}: invalid author-file schema")
        for atom in content["atoms"]:
            identifier = atom.get("id", "<no id>")
            errors.extend(
                f"{path.name}/{identifier}: {error}" for error in atom_errors(atom, nodes)
            )
            if identifier in ids:
                errors.append(f"duplicate atom ID: {identifier}")
            ids.add(identifier)
            atoms.append(atom)
    counts = {identifier: sum(a["node_id"] == identifier for a in atoms) for identifier in nodes}
    if not allow_partial:
        errors.extend(
            f"{identifier}: needs at least 4 distinct atoms, found {count}"
            for identifier, count in counts.items()
            if count < 4
        )
    if errors:
        raise ValueError("\n".join(errors))
    return graph, atoms, counts


def diagram(v: dict, width: int) -> str:
    drawing = SVG(width, v["title"], v["caption"])
    top, kind = drawing.top, v["kind"]
    columns = (width - 60) // 8
    if kind == "flow":
        boxes = []
        edges = v.get(
            "edges", [{"from": i, "to": i + 1, "label": ""} for i in range(len(v["nodes"]) - 1)]
        )
        edge_columns = max(8, (width - 72) // 14)
        for index, node in enumerate(v["nodes"]):
            label = f"{index + 1}. {node['label']}"
            label_lines = len(text_lines(label, columns - 5))
            detail_lines = len(text_lines(node["detail"], columns - 5))
            height = 28 + label_lines * 25 + detail_lines * 22
            boxes.append((top, height))
            drawing.rect(30, top, width - 80, height)
            drawing.text(46, top + 26, label, columns=columns - 5, weight=650)
            drawing.text(
                46,
                top + 31 + label_lines * 25,
                node["detail"],
                15,
                columns=columns - 5,
                color="#425a6d",
            )
            gap = max(
                [38]
                + [
                    22 + 19 * len(text_lines(edge.get("label", ""), edge_columns))
                    for edge in edges
                    if edge["from"] == index and edge["to"] == index + 1
                ]
            )
            top += height + gap
        for edge in edges:
            start, end = edge["from"], edge["to"]
            if end == start + 1:
                drawing.line(
                    width / 2 - 10,
                    boxes[start][0] + boxes[start][1] + 3,
                    width / 2 - 10,
                    boxes[end][0] - 5,
                    arrow=True,
                )
                if edge.get("label"):
                    drawing.text(
                        width / 2 + 3,
                        boxes[start][0] + boxes[start][1] + 20,
                        edge["label"],
                        13,
                        columns=edge_columns,
                    )
            else:
                x = width - 28
                y1, y2 = boxes[start][0] + boxes[start][1] / 2, boxes[end][0] + boxes[end][1] / 2
                drawing.line(width - 50, y1, x, y1, COLORS[1])
                drawing.line(x, y1, x, y2, COLORS[1])
                drawing.line(x, y2, width - 50, y2, COLORS[1], arrow=True)
                if edge.get("label"):
                    top += (
                        drawing.text(
                            30,
                            top,
                            f"{start + 1} → {end + 1}：{edge['label']}",
                            14,
                            columns=columns,
                        )
                        + 12
                    )
    elif kind == "compare":
        for index, panel in enumerate(v["panels"]):
            height = (
                42
                + len(text_lines(panel["title"], columns)) * 25
                + sum(24 * len(text_lines(line, columns - 2)) + 10 for line in panel["lines"])
            )
            drawing.rect(20, top, width - 40, height, fill="#f5f8fa", stroke=COLORS[index])
            top += (
                drawing.text(
                    36,
                    top + 27,
                    panel["title"],
                    17,
                    columns=columns,
                    color=COLORS[index],
                    weight=650,
                )
                + 36
            )
            for line in panel["lines"]:
                top += drawing.text(36, top, "· " + line, 16, columns=columns - 2) + 10
            top += 28
    elif kind == "matrix":
        values = v["values"]
        left, right = 84, width - 20
        cell = min(70, (right - left) / len(values[0]))
        header_columns = max(4, int(cell // 7))
        header_height = (
            max(len(text_lines(label, header_columns)) for label in v["column_labels"]) * 19
        )
        header_top = top + 18
        top += header_height + 34
        for index, label in enumerate(v["column_labels"]):
            drawing.text(
                left + cell * (index + 0.5),
                header_top,
                label,
                13,
                anchor="middle",
                columns=header_columns,
            )
        bound = max(abs(value) for row in values for value in row) or 1
        for row_index, row in enumerate(values):
            row_height = max(58, len(text_lines(v["row_labels"][row_index], 8)) * 19 + 18)
            drawing.text(
                left - 8, top + 26, v["row_labels"][row_index], 13, anchor="end", columns=8
            )
            for column, value in enumerate(row):
                strength = abs(value) / bound
                base = (34, 109, 169) if value >= 0 else (179, 76, 28)
                fill = "#" + "".join(
                    f"{round(255 * (1 - 0.58 * strength) + component * 0.58 * strength):02x}"
                    for component in base
                )
                drawing.rect(
                    left + column * cell, top, cell, row_height, fill=fill, stroke="#fff", radius=2
                )
                drawing.text(
                    left + cell * (column + 0.5), top + 33, number(value), 13, anchor="middle"
                )
            top += row_height
        top += 28
        top += drawing.text(
            20,
            top,
            v.get("note", "色深表示数值大小；具体值以单元格数字为准。"),
            14,
            columns=columns + 2,
        )
    elif kind == "timeline":
        events = v["events"]
        minimum = min(0, min(e["start"] for e in events))
        maximum = max(e["end"] for e in events)
        maximum = maximum if maximum > minimum else minimum + 1
        left, right = 28, width - 30

        def x(value):
            return left + (value - minimum) / (maximum - minimum) * (right - left)

        for index, event in enumerate(events):
            top += drawing.text(left, top + 18, event["label"], 16, columns=columns, weight=600) + 8
            drawing.line(left, top + 12, right, top + 12, "#cbd6df")
            drawing.rect(
                x(event["start"]),
                top,
                max(2, x(event["end"]) - x(event["start"])),
                24,
                fill=COLORS[index],
                stroke=COLORS[index],
                radius=3,
            )
            drawing.text(
                left,
                top + 48,
                f"{number(event['start'])} → {number(event['end'])} {v['unit']}",
                14,
                columns=columns,
            )
            top += 76
        drawing.text(
            left,
            top,
            f"共同时间轴：{number(minimum)} → {number(maximum)} {v['unit']}",
            14,
            columns=columns,
        )
        top += 30
        top += drawing.text(20, top, v.get("note", ""), 14, columns=columns + 2)
    elif kind == "bars":
        values, labels = v["values"], v["labels"]
        minimum, maximum = min(0, min(values)), max(0, max(values))
        if minimum == maximum:
            maximum = minimum + 1
        left, right = 28, width - 64

        def x(value):
            return left + (value - minimum) / (maximum - minimum) * (right - left)

        for index, (label, value) in enumerate(zip(labels, values)):
            top += drawing.text(28, top + 16, label, 16, columns=columns, weight=600) + 10
            drawing.line(x(0), top - 5, x(0), top + 29, "#778797")
            drawing.rect(
                min(x(0), x(value)),
                top,
                max(1, abs(x(value) - x(0))),
                24,
                fill=COLORS[index],
                stroke=COLORS[index],
                radius=2,
            )
            drawing.text(right + 8, top + 18, number(value), 14, columns=8)
            top += 44
        top += drawing.text(28, top + 18, v["axis_label"], 14, columns=columns) + 24
        top += drawing.text(20, top, v.get("note", ""), 14, columns=columns + 2)
    elif kind in {"plot", "vectors"}:
        # Legends use real text rather than labels placed over intersecting data.
        items = v["series"] if kind == "plot" else v["vectors"]
        for index, item in enumerate(items):
            detail = (
                item["label"]
                if kind == "plot"
                else f"{item['label']}: ({number(item['x'])}, {number(item['y'])}) {v['unit']}"
            )
            drawing.line(22, top + 7, 42, top + 7, COLORS[index], width=3)
            top += drawing.text(50, top + 12, detail, 14, columns=(width - 70) // 7) + 7
        left, right = 52, width - 26
        if kind == "plot":
            points = [p for s in items for p in s["points"]]
            xmin, xmax = min(p[0] for p in points), max(p[0] for p in points)
            ymin, ymax = min(0, min(p[1] for p in points)), max(0, max(p[1] for p in points))
            xmax = xmax if xmax > xmin else xmin + 1
            ymax = ymax if ymax > ymin else ymin + 1
            padding = (ymax - ymin) * 0.1
            ymin, ymax = ymin - padding if ymin < 0 else 0, ymax + padding
            xlabel, ylabel = v["x_label"], v["y_label"]
            height = 225 if width < 600 else 285
        else:
            # Scale to the actual units: a 0.15 m capture point must not shrink
            # into an unreadable dot merely because its coordinates are < 1.
            bound = (max(max(abs(a["x"]), abs(a["y"])) for a in items) or 1) * 1.25
            xmin = ymin = -bound
            xmax = ymax = bound
            height = right - left  # Same scale on x and y: preserve angles.
            xlabel, ylabel = f"x ({v['unit']})", f"y ({v['unit']})"
        tick_chars = max(len(number(ymin + (ymax - ymin) * i / 3)) for i in range(4))
        left = max(58, 8 * tick_chars + 12)
        if kind == "vectors":
            height = right - left
        top += drawing.text(22, top + 17, ylabel, 14, columns=columns + 2) + 15
        bottom = top + height

        def x(value):
            return left + (value - xmin) / (xmax - xmin) * (right - left)

        def y(value):
            return bottom - (value - ymin) / (ymax - ymin) * height

        drawing.rect(left, top, right - left, height, fill="#fff", radius=0)
        ticks = 3 if width < 600 else 4
        for index in range(ticks + 1):
            vx = xmin + (xmax - xmin) * index / ticks
            vy = ymin + (ymax - ymin) * index / ticks
            drawing.line(x(vx), top, x(vx), bottom, "#e2e9ee")
            drawing.line(left, y(vy), right, y(vy), "#e2e9ee")
            drawing.text(x(vx), bottom + 24, number(vx), 13, anchor="middle")
            drawing.text(left - 7, y(vy) + 5, number(vy), 13, anchor="end")
        if xmin <= 0 <= xmax:
            drawing.line(x(0), top, x(0), bottom, "#526777")
        if ymin <= 0 <= ymax:
            drawing.line(left, y(0), right, y(0), "#526777")
        if kind == "plot":
            for index, series in enumerate(items):
                for before, after in zip(series["points"], series["points"][1:]):
                    drawing.line(
                        x(before[0]), y(before[1]), x(after[0]), y(after[1]), COLORS[index], 2.5
                    )
                for px, py in series["points"]:
                    drawing.circle(x(px), y(py), color=COLORS[index])
        else:
            for index, vector in sorted(
                enumerate(items),
                key=lambda item: math.hypot(item[1]["x"], item[1]["y"]),
                reverse=True,
            ):
                drawing.line(
                    x(0), y(0), x(vector["x"]), y(vector["y"]), COLORS[index], 3, arrow=True
                )
                drawing.circle(x(vector["x"]), y(vector["y"]), 3, COLORS[index])
        top = bottom + 49
        top += drawing.text(width / 2, top, xlabel, 14, columns=columns, anchor="middle") + 10
        if kind == "vectors":
            top += drawing.text(20, top, v.get("note", ""), 14, columns=columns + 2)
    return drawing.finish(top)


def relative_link(source: Path, target: Path) -> str:
    return os.path.relpath(target, source.parent).replace(os.sep, "/")


def picture(atom: dict, page: Path) -> str:
    base = relative_link(page, ASSETS / atom["id"])
    return f'''<figure class="atlas-visual" tabindex="0" aria-label="{esc(atom["visual"]["title"])}；窄屏可在图内横向滚动">
<picture>
<source media="(max-width: 600px)" srcset="{base}-mobile.svg">
<img src="{base}.svg" alt="{esc(atom["visual"]["title"] + "：" + atom["visual"]["caption"])}" loading="lazy">
</picture>
<figcaption>{esc(atom["visual"]["caption"])}</figcaption>
</figure>'''


def data_table(v: dict) -> str:
    """Expose unrounded chart inputs for accessibility and hand verification."""
    kind = v["kind"]
    if kind == "plot":
        header = ["曲线", v["x_label"], v["y_label"]]
        rows = [[s["label"], x, y] for s in v["series"] for x, y in s["points"]]
    elif kind == "matrix":
        header = ["行 / 列"] + v["column_labels"]
        rows = [[label] + values for label, values in zip(v["row_labels"], v["values"])]
    elif kind == "bars":
        header, rows = ["项目", v["axis_label"]], list(zip(v["labels"], v["values"]))
    elif kind == "vectors":
        header = ["向量", f"x ({v['unit']})", f"y ({v['unit']})"]
        rows = [[a["label"], a["x"], a["y"]] for a in v["vectors"]]
    elif kind == "timeline":
        header = ["事件", f"开始 ({v['unit']})", f"结束 ({v['unit']})"]
        rows = [[a["label"], a["start"], a["end"]] for a in v["events"]]
    else:
        return ""

    def row(values):
        return (
            "| "
            + " | ".join(str(x).replace("|", "&#124;").replace("\n", " ") for x in values)
            + " |"
        )

    table = "\n".join([row(header), row(["---"] * len(header))] + [row(r) for r in rows])
    note = "图上数值可能为便于阅读而取近似值，以下保留作图输入。"
    if kind == "plot":
        note += "线段的含义以本图图注和读图说明为准，不应自行解释为实测连续轨迹。"
    return (
        '<details class="atlas-data" markdown="1">\n<summary>查看作图数据，自己复算</summary>\n\n'
        + note
        + "\n\n"
        + table
        + "\n\n</details>"
    )


def node_lesson(node: dict, atoms: list[dict], nodes: dict) -> str:
    page = LESSONS / node["id"] / "index.md"
    back = relative_link(page, LESSONS / "index.md")
    original = relative_link(page, ROOT / node["document"])
    lines = [
        f"# {node['title_zh']}：逐点细解",
        f"<!-- {GENERATED_MARKER} -->",
        f"[全部知识点]({back}) · [返回原课程]({original})",
        f"{node['title']} · 本页拆成 **{len(atoms)} 个小知识点**。",
        "先阅读直觉和原理，再独立完成算例、自测；图是解释工具，不是已掌握或真机验证的证明。",
    ]
    if node["prerequisites"]:
        links = [
            f"[{nodes[p]['title_zh']}]({relative_link(page, LESSONS / p / 'index.md')})"
            for p in node["prerequisites"]
        ]
        lines += ["## 前置知识", " → ".join(links)]
    if node["id"] in LAB_CONNECTIONS:
        lab, task = LAB_CONNECTIONS[node["id"]]
        target = relative_link(page, ROOT / "docs/learning-lab-cn.md") + "#" + lab
        lines += [
            "## 改一个参数试试看",
            f"{task}\n\n[打开对应交互实验]({target})。滑块在文档站运行，GitHub 文件预览提供静态推导；不连接机器人。",
        ]
    lines += [
        "## 本页知识点",
        "\n".join(f"{i + 1}. [{a['title']}](#{a['id']})" for i, a in enumerate(atoms)),
    ]
    for index, atom in enumerate(atoms, 1):
        lines += [
            f'<a id="{atom["id"]}"></a>',
            f"## {index}. {atom['title']}",
            f"**{atom['english']}**",
            "**需要先懂：**" + ("、".join(atom["prerequisites"]) or "无需额外前置知识。"),
            "### 一句话直觉",
            atom["intuition"],
            "### 原理拆开看",
            "\n".join(f"{i + 1}. {step}" for i, step in enumerate(atom["mechanism"])),
            "### 手算或追踪一个例子",
            "\n".join(f"{i + 1}. {step}" for i, step in enumerate(atom["worked_example"])),
            "### 用图理解",
            picture(atom, page),
            "\n".join(f"- {step}" for step in atom["reading"]),
            data_table(atom["visual"]),
            "### 容易混淆的地方",
            f"**常见误解：**{atom['misconception']['wrong']}",
            f"**为什么不成立：**{atom['misconception']['why']}",
            f"**正确理解：**{atom['misconception']['right']}",
            "### 自测",
            atom["check"]["question"],
            '<details class="atlas-answer" markdown="1">\n<summary>展开答案与推理</summary>\n\n'
            + atom["check"]["answer"]
            + "\n\n</details>",
            "**原始资料：**" + " · ".join(f"[{s['title']}]({s['url']})" for s in atom["sources"]),
        ]
    lines += [
        "## 从理解走向证据",
        f"本节点原有验收要求：{node['assessment_zh']}",
        f"完成图解自测后，回到[原课程]({original})运行对应示例并保留证据；浏览页面和查看答案不会自动获得课程晋级。",
    ]
    return "\n\n".join(lines) + "\n"


def outputs(graph, atoms, counts) -> dict[Path, str]:
    files: dict[Path, str] = {}
    nodes = {n["id"]: n for n in graph["nodes"]}
    grouped = {identifier: [a for a in atoms if a["node_id"] == identifier] for identifier in nodes}
    for identifier, group in grouped.items():
        if group:
            files[LESSONS / identifier / "index.md"] = node_lesson(nodes[identifier], group, nodes)
    for atom in atoms:
        files[ASSETS / f"{atom['id']}.svg"] = diagram(atom["visual"], 720)
        files[ASSETS / f"{atom['id']}-mobile.svg"] = diagram(atom["visual"], 360)
    complete = all(count >= 4 for count in counts.values())
    index = [
        "# 把每个知识点讲明白",
        f"<!-- {GENERATED_MARKER} -->",
        "[原知识体系](../knowledge-system/README_CN.md) · [基础课程](../foundations/00-roadmap.md) · [交互实验室](../learning-lab-cn.md)",
        "[本轮范围与验证记录](../KNOWLEDGE_ATLAS_REVIEW.md)：区分内容覆盖、独立算例审查、离线图像检查与尚未完成的浏览器验收。",
        f"以现有 **{len(nodes)} 个知识节点**为范围，拆解为 **{len(atoms)} 个小知识点**。每项都有逐步原理、具体算例、可离线阅读的图、误区纠偏和自测答案。",
        "这不是一份需要死记的术语表：先指出自己不懂的环节，再用算例验证，最后回原课程完成实际任务。",
        "这些图中的简化参数和数据用于教学，不是新的模型评测或真机结果。覆盖数表示内容结构，不证明学习者已经成为专家。",
        "English orientation: this is a Chinese-led close-up companion to the existing curriculum, with English terminology retained. The original English courses remain available. It covers the repository's declared nodes, not every topic in embodied AI.",
    ]
    if not complete:
        index += ["> 当前为编写中的局部预览，尚未覆盖全部节点，不作为完整交付。"]
    index += [
        "## 怎么使用",
        "1. 从下方选择不熟悉的知识点，先检查前置知识。\n2. 读直觉，再逐步解释每一步为什么成立。\n3. 遮住结果完成算例，用图检查自己的预测。\n4. 独立回答自测后再展开答案，回原课程留下代码或实验记录。",
        "## 按领域查找",
    ]
    for domain in graph["domains"]:
        relevant = [n for n in graph["nodes"] if n["domain"] == domain["id"]]
        index += [
            f"### {domain['title_zh']} · {domain['title']}",
            domain["question_zh"],
            "| 知识节点 | 小知识点 | 阅读入口 |\n|---|---:|---|\n"
            + "\n".join(
                f"| {n['title_zh']} | {counts[n['id']]} | [逐点细解]({n['id']}/index.md) |"
                if counts[n["id"]]
                else f"| {n['title_zh']} | 0 | 编写中 |"
                for n in relevant
            ),
        ]
    files[LESSONS / "index.md"] = "\n\n".join(index) + "\n"
    coverage = {
        "schema_version": 1,
        "boundary": "Coverage of the 45 declared repository nodes only; not exhaustive science, learner mastery, or visual acceptance.",
        "complete": complete,
        "nodes": counts,
        "atoms": len(atoms),
        "diagram_kinds": {
            kind: sum(a["visual"]["kind"] == kind for a in atoms) for kind in sorted(KINDS)
        },
        "responsive_svg_files": 2 * len(atoms),
        "source_sha256": hashlib.sha256(
            json.dumps(atoms, ensure_ascii=False, sort_keys=True).encode()
        ).hexdigest(),
        "lessons": {
            identifier: f"docs/knowledge-atlas/{identifier}/index.md"
            for identifier, count in counts.items()
            if count
        },
    }
    files[ROOT / "knowledge/atlas-coverage.json"] = (
        json.dumps(coverage, ensure_ascii=False, indent=2) + "\n"
    )
    return files


def run(check=False, allow_partial=False) -> int:
    graph, atoms, counts = load_atoms(allow_partial)
    generated = outputs(graph, atoms, counts)
    for path, text in generated.items():
        if path.suffix == ".svg":
            ET.fromstring(text)
        if check:
            if not path.is_file() or path.read_text(encoding="utf-8") != text:
                raise ValueError(f"Missing/stale generated output: {path.relative_to(ROOT)}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
    print(
        f"Knowledge atlas {'verified' if check else 'generated'}: {len(atoms)} atoms; {sum(count > 0 for count in counts.values())}/{len(counts)} nodes; {2 * len(atoms)} responsive SVGs. Coverage is not mastery or visual acceptance."
    )
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--allow-partial", action="store_true")
    args = parser.parse_args()
    try:
        return run(args.check, args.allow_partial)
    except (ValueError, KeyError, TypeError, OSError) as error:
        print(error, file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
